import { randomUUID } from 'crypto';
import { writeFile } from 'fs/promises';
import type { OwletteClient } from '../lib/client';

export interface MachineSummary {
  id: string;
  name: string;
  online: boolean;
  lastHeartbeat: string | null;
  agentVersion: string | null;
  os: string | null;
  currentRoosts: Array<{ roostId: string; name: string; currentVersionId: string | null }>;
}

export interface MachineDetail extends Omit<MachineSummary, 'currentRoosts'> {
  siteId: string;
  hostname: string | null;
  metrics: unknown | null;
  processes: Array<Record<string, unknown>>;
}

export interface MachineDeployment {
  roostId: string;
  name: string;
  currentVersionId: string | null;
  previousVersionId: string | null;
  extractPath: string | null;
  reportedVersionId: string | null;
  reportedStatus: string | null;
  reportedAt: string | null;
}

/* --------------------------------------------------------------------- */
/*  command dispatch / poll types                                        */
/* --------------------------------------------------------------------- */

export type MachineCommandType =
  | 'reboot_machine'
  | 'shutdown_machine'
  | 'capture_screenshot';

export type MachineCommandStatus =
  | 'pending'
  | 'in_progress'
  | 'completed'
  | 'failed';

export interface DispatchCommandResult {
  commandId: string;
  status: MachineCommandStatus;
}

export interface CommandStatus {
  commandId: string;
  status: MachineCommandStatus;
  result?: Record<string, unknown>;
  error?: string;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface CaptureScreenshotOptions {
  /** Monitor selector — `'all'`, `'primary'`, or a 0-based index. Default `'primary'`. */
  monitor?: 'all' | 'primary' | number;
  /** Override the dispatch's idempotency key. */
  idempotencyKey?: string;
  /** How long to keep polling before giving up. Default 60_000ms (40 polls × 1500ms). */
  timeoutMs?: number;
  /** Override poll interval. Default 1500ms. */
  pollIntervalMs?: number;
  /** When set, the captured PNG is written here and the function returns its path. */
  downloadTo?: string;
  /** Forwarded to the underlying screenshot fetch for cancellation. */
  signal?: AbortSignal;
}

export interface CaptureScreenshotResult {
  commandId: string;
  status: 'completed';
  /** Signed URL for the screenshot — short-lived, regenerated by the api on each poll. */
  screenshotUrl: string;
  /** ISO timestamp at which the signed URL expires. */
  expiresAt: string | null;
  /** Raw bytes of the PNG when `downloadTo` is omitted. */
  bytes?: Buffer;
  /** Path the PNG was written to when `downloadTo` is provided. */
  downloadedTo?: string;
  /** Full result envelope echoed back from the server. */
  result: Record<string, unknown>;
}

const DEFAULT_POLL_INTERVAL_MS = 1500;
const DEFAULT_MAX_POLLS = 40;

/* --------------------------------------------------------------------- */
/*  resource                                                             */
/* --------------------------------------------------------------------- */

export class Machines {
  constructor(private readonly client: OwletteClient) {}

  async list(siteId: string): Promise<MachineSummary[]> {
    const res = await this.client.request<{ machines: MachineSummary[] }>(
      `/api/sites/${encodeURIComponent(siteId)}/machines`,
    );
    return res.data.machines;
  }

  async get(siteId: string, machineId: string): Promise<MachineDetail> {
    const res = await this.client.request<MachineDetail>(
      `/api/sites/${encodeURIComponent(siteId)}/machines/${encodeURIComponent(machineId)}`,
    );
    return res.data;
  }

  async deployments(siteId: string, machineId: string): Promise<MachineDeployment[]> {
    const res = await this.client.request<{ deployments: MachineDeployment[] }>(
      `/api/sites/${encodeURIComponent(siteId)}/machines/${encodeURIComponent(machineId)}/deployments`,
    );
    return res.data.deployments;
  }

  /**
   * Queue an operator-safe machine command. The endpoint enforces an
   * allowlist (`reboot_machine`, `shutdown_machine`, `capture_screenshot`);
   * any other type → 400 `unsupported_command_type` from the server.
   */
  async dispatchCommand(
    siteId: string,
    machineId: string,
    type: MachineCommandType,
    params: Record<string, unknown> = {},
    opts: { idempotencyKey?: string; timeoutSeconds?: number } = {},
  ): Promise<DispatchCommandResult> {
    const body: Record<string, unknown> = { type };
    if (Object.keys(params).length > 0) body.params = params;
    if (opts.timeoutSeconds !== undefined) body.timeout_seconds = opts.timeoutSeconds;

    const res = await this.client.request<{ ok: true; data: DispatchCommandResult }>(
      `/api/sites/${encodeURIComponent(siteId)}/machines/${encodeURIComponent(machineId)}/commands`,
      {
        method: 'POST',
        body,
        idempotencyKey:
          opts.idempotencyKey ?? `sdk-machines-dispatch-command-${randomUUID()}`,
      },
    );
    return res.data.data;
  }

  /**
   * Poll a queued command's status. For completed `capture_screenshot`
   * commands the server mints a fresh signed URL on every read — never
   * cache it, always pull a new one when you need to download.
   */
  async getCommand(
    siteId: string,
    machineId: string,
    commandId: string,
  ): Promise<CommandStatus> {
    const res = await this.client.request<{ ok: true; data: CommandStatus }>(
      `/api/sites/${encodeURIComponent(siteId)}/machines/${encodeURIComponent(machineId)}/commands/${encodeURIComponent(commandId)}`,
    );
    return res.data.data;
  }

  /**
   * Capture a screenshot end-to-end: dispatch → poll until terminal →
   * fetch the signed URL into memory or onto disk.
   */
  async captureScreenshot(
    siteId: string,
    machineId: string,
    opts: CaptureScreenshotOptions = {},
  ): Promise<CaptureScreenshotResult> {
    const monitor = opts.monitor ?? 'primary';
    const params: Record<string, unknown> = { monitor };

    const dispatchOpts: { idempotencyKey?: string; timeoutSeconds?: number } = {};
    if (opts.idempotencyKey !== undefined) {
      dispatchOpts.idempotencyKey = opts.idempotencyKey;
    }
    const dispatch = await this.dispatchCommand(
      siteId,
      machineId,
      'capture_screenshot',
      params,
      dispatchOpts,
    );

    const pollIntervalMs = opts.pollIntervalMs ?? DEFAULT_POLL_INTERVAL_MS;
    const maxPolls =
      opts.timeoutMs !== undefined
        ? Math.max(1, Math.ceil(opts.timeoutMs / pollIntervalMs))
        : DEFAULT_MAX_POLLS;

    let status: CommandStatus | null = null;
    for (let i = 0; i < maxPolls; i++) {
      // First poll fires immediately so a fast-completing capture can
      // return without paying a full sleep cycle.
      if (i > 0) await delay(pollIntervalMs, opts.signal);
      const current = await this.getCommand(siteId, machineId, dispatch.commandId);
      if (current.status === 'completed' || current.status === 'failed') {
        status = current;
        break;
      }
      status = current;
    }

    if (!status || status.status !== 'completed') {
      const detail =
        status?.error ??
        `screenshot did not complete within ${maxPolls * pollIntervalMs}ms`;
      throw new Error(`captureScreenshot: ${detail}`);
    }

    const result = status.result ?? {};
    const screenshotUrl =
      typeof result.screenshot_url === 'string' ? result.screenshot_url : null;
    if (!screenshotUrl) {
      throw new Error(
        'captureScreenshot: command completed without a screenshot_url; ' +
          'the agent may not have uploaded the image',
      );
    }

    const fetchInit: RequestInit = {};
    if (opts.signal) fetchInit.signal = opts.signal;
    const imgRes = await this.client._fetch(screenshotUrl, fetchInit);
    if (!imgRes.ok) {
      throw new Error(
        `captureScreenshot: signed-url fetch failed with http ${imgRes.status}`,
      );
    }
    const arrayBuf = await imgRes.arrayBuffer();
    const bytes = Buffer.from(arrayBuf);

    const expiresAt =
      typeof result.expires_at === 'string' ? result.expires_at : null;

    if (opts.downloadTo) {
      await writeFile(opts.downloadTo, new Uint8Array(bytes));
      return {
        commandId: dispatch.commandId,
        status: 'completed',
        screenshotUrl,
        expiresAt,
        downloadedTo: opts.downloadTo,
        result,
      };
    }

    return {
      commandId: dispatch.commandId,
      status: 'completed',
      screenshotUrl,
      expiresAt,
      bytes,
      result,
    };
  }
}

/* --------------------------------------------------------------------- */
/*  helpers                                                              */
/* --------------------------------------------------------------------- */

async function delay(ms: number, signal: AbortSignal | undefined): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new Error('captureScreenshot: aborted'));
      return;
    }
    const timer = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    const onAbort = (): void => {
      clearTimeout(timer);
      reject(new Error('captureScreenshot: aborted'));
    };
    signal?.addEventListener('abort', onAbort, { once: true });
  });
}
