/**
 * Role helpers — apply in a spec with `test.use(roleState('admin'))`.
 *
 * Each storageState file is generated by global-setup via a real login
 * against the dev server in emulator mode. Specs that need a given role
 * simply reference the file; Playwright loads cookies + localStorage +
 * IndexedDB on new contexts automatically.
 */

import { join } from 'path';
import type { TestRole } from './seed';

const FIXTURES_DIR = join(__dirname, '..', 'fixtures');

/**
 * Convenience helper for `test.use({ storageState: ... })`. Returns the
 * full path to the fixture for the given role.
 */
export function roleState(role: TestRole): { storageState: string } {
  return { storageState: join(FIXTURES_DIR, `${role}.json`) };
}
